/**
 * Listener Flows Service
 * 
 * Implements the complete 10-step listener room connection flow as specified
 * in DJ_ROOM_CREATION_FLOW_HOW_ITS_SUPPOSED_TO_BE.md (steps 1-10a + 6b-7b error handling).
 * 
 * Uses room store for state management and domain schemas for type safety.
 */

import { Effect, pipe, Option } from 'effect'
import type { RoomStore } from '../../stores/room.store'
import { 
  type ListenerState,
  createInitialListenerState 
} from '../../domain/schemas/listener.schema'
import { 
  type RoomMetadata,
} from '../../domain/schemas/room.schema'
import type { 
  ListenerEvent, 
  ListenerCommand
} from '../websocket/schemas/websocket'
import type { RoomInfo } from '../generated/hushFMAPI.schemas'
import { 
  ListenerFlowError,
  AudioPlaybackError 
} from '../../domain/errors'
import { createAndLoadDevice } from '../mediasoup/device.service'
import { createReceiveTransportWithEvents } from '../mediasoup/transport.service'
import { createAudioConsumer } from '../mediasoup/consumer.service'

/**
 * Listener join result
 */
export interface ListenerJoinResult {
  listenerId: string
  roomMetadata: RoomMetadata
  audioStream: MediaStream
}

/**
 * Request to join a room as a listener
 */
export interface JoinRoomRequest {
  roomId: string
  listenerName: string
  roomInfo: RoomInfo // From lobby store
}

/**
 * Join room as listener - implements complete 10-step flow
 * 
 * Flow steps:
 * 1. Request joining room from lobby → creates listener websocket
 * 2. Backend creates webrtc receiver transport → sends params
 * 3. Frontend creates receive transport from params  
 * 4. Frontend sends device RTP capabilities to backend
 * 5. Backend checks canConsume() → creates consumer if compatible
 * 6a. Backend sends consumer params (id, kind, rtp) → continue to 7a
 * 6b. Backend returns error if router incompatible → go to 7b
 * 7a. Frontend creates client consumer → fires connect event
 * 7b. Frontend shows error, cancels joining, returns to lobby
 * 8a. Frontend connect handler sends DTLS params to backend
 * 9a. Backend connects receiver transport with DTLS params
 * 10a. Media streaming starts
 */
export const joinRoomAsListener = (
  roomStore: RoomStore,
  lobbyWebSocket: WebSocket,
  request: JoinRoomRequest
): Effect.Effect<ListenerJoinResult, ListenerFlowError> =>
  pipe(
    Effect.gen(function* (_) {
      console.info('🎧 Starting listener join flow for room:', request.roomId)
      
      // Generate listener ID
      const listenerId = `listener_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`
      
      // Initialize listener state in room store
      const initialListenerState = createInitialListenerState()
      const listenerState: ListenerState = {
        ...initialListenerState,
        currentStep: 'requesting_join',
        flowStartedAt: Option.some(new Date())
      }
      
      roomStore.actions.addListener(listenerState)
      
      // The actual listener ID is generated by the store
      const actualListenerId = (roomStore.listeners[roomStore.listeners.length - 1] as any)?.id || listenerId
      
      try {
        // Step 1: Request joining room from lobby → creates listener websocket
        console.info('✅ Step 1: Requesting to join room via lobby websocket')
        roomStore.actions.setListenerFlowStep(listenerId, 'requesting_join')
        
        const joinCommand: ListenerCommand = {
          type: 'requestJoin',
          roomId: request.roomId,
          rtpCapabilities: {} // Will be updated after device load
        }
        
        // Send join request and wait for listener websocket creation
        lobbyWebSocket.send(JSON.stringify(joinCommand))
        
        // Wait for joinRoomResponse with listener websocket URL
        const joinResponse = yield* _(waitForJoinRoomResponse(lobbyWebSocket, request.roomId))
        
        // Connect to listener websocket
        const listenerWebSocket = new WebSocket(joinResponse.listenerWebSocketUrl)
        yield* _(waitForWebSocketOpen(listenerWebSocket))
        
        // Update listener state with websocket
        roomStore.actions.updateListener(actualListenerId, {
          websocket: {
            ...initialListenerState.websocket,
            websocket: Option.some(listenerWebSocket),
            connectionState: 'connected',
            roomId: Option.some(request.roomId),
            url: Option.some(joinResponse.listenerWebSocketUrl),
            connectedAt: Option.some(new Date())
          }
        })
        
        // Step 2: Backend creates webrtc receiver transport → sends params
        console.info('✅ Step 2: Waiting for transport params from backend')
        roomStore.actions.setListenerFlowStep(listenerId, 'waiting_transport')
        
        const transportParams = yield* _(waitForTransportParams(listenerWebSocket))
        
        // Step 3: Frontend creates receive transport from params
        console.info('✅ Step 3: Creating receive transport from params')
        roomStore.actions.setListenerFlowStep(listenerId, 'creating_transport')
        
        // Create and load device with RTP capabilities
        const device = yield* _(createAndLoadDevice(transportParams.rtpCapabilities).pipe(
          Effect.mapError(error => new ListenerFlowError({
            cause: `Failed to create device: ${String(error)}`,
            step: 'creating_transport',
            stepNumber: 3,
            recoverable: false,
            context: { timestamp: new Date(), operation: 'create_device', details: { listenerId, error } }
          }))
        ))
        
        // Create receive transport  
        const receiveTransport = yield* _(createReceiveTransportWithEvents(device, transportParams, {
          onConnect: async (dtlsParameters) => {
            console.info('✅ Step 8a: Transport connect event - sending DTLS params')
            const dtlsCommand: ListenerCommand = {
              type: 'connectListenerTransport',
              transportId: transportParams.id,
              dtlsParameters
            }
            listenerWebSocket.send(JSON.stringify(dtlsCommand))
          }
        }).pipe(
          Effect.mapError(error => new ListenerFlowError({
            cause: `Failed to create receive transport: ${String(error)}`,
            step: 'creating_transport',
            stepNumber: 3,
            recoverable: false,
            context: { timestamp: new Date(), operation: 'create_transport', details: { listenerId, error } }
          }))
        ))
        
        // Update listener state with device and transport
        roomStore.actions.updateListener(actualListenerId, {
          device: {
            device: Option.some(device),
            loaded: true,
            rtpCapabilities: Option.some(device.rtpCapabilities),
            routerRtpCapabilities: Option.some(transportParams.rtpCapabilities),
            loadError: Option.none(),
            handlerName: Option.some(device.handlerName),
            canProduce: device.canProduce('audio'),
            canConsume: true
          },
          receiveTransport: {
            ...initialListenerState.receiveTransport,
            transport: Option.some(receiveTransport),
            id: Option.some(transportParams.id),
            connectionState: 'new',
            transportOptions: Option.some(transportParams),
            connected: false
          }
        })
        
        console.info('Device and transport created successfully')
        
        // Step 4: Frontend sends device RTP capabilities to backend
        console.info('✅ Step 4: Sending device RTP capabilities to backend')
        roomStore.actions.setListenerFlowStep(listenerId, 'sending_capabilities')
        
        const rtpCapabilitiesCommand: ListenerCommand = {
          type: 'requestConsumer',
          rtpCapabilities: device.rtpCapabilities
        }
        listenerWebSocket.send(JSON.stringify(rtpCapabilitiesCommand))
        
        // Step 5: Backend checks canConsume() → creates consumer if compatible
        console.info('✅ Step 5: Waiting for backend consumer compatibility check')
        roomStore.actions.setListenerFlowStep(listenerId, 'waiting_consumer')
        
        // Wait for either consumer params (6a) or error (6b)
        const consumerResult = yield* _(waitForConsumerResult(listenerWebSocket))
        
        if (consumerResult.type === 'error') {
          // Step 6b + 7b: Backend returns error → show error, cancel joining, return to lobby
          console.error('❌ Step 6b/7b: Router incompatible, canceling join')
          roomStore.actions.setListenerError(listenerId, consumerResult.error, 'error')
          
          // Cleanup and return to lobby
          yield* _(roomStore.actions.disconnectFromRoom())
          
          yield* _(Effect.fail(new ListenerFlowError({
            cause: `Room join failed: ${consumerResult.error}`,
            step: 'error',
            stepNumber: 6,
            recoverable: false,
            context: { timestamp: new Date(), operation: 'consumer_check', details: { listenerId, roomIncompatible: true } }
          })))
        }
        
        // Step 6a: Backend sends consumer params (id, kind, rtp) → continue to 7a
        if (consumerResult.type !== 'success') {
          throw new Error('Unexpected consumer result type')
        }
        const consumerParams = consumerResult.params
        console.info('✅ Step 6a: Received consumer params from backend')
        
        // Step 7a: Frontend creates client consumer → fires connect event
        console.info('✅ Step 7a: Creating client-side consumer')
        roomStore.actions.setListenerFlowStep(listenerId, 'creating_consumer')
        
        // Create consumer using the audio consumer service
        const { consumer } = yield* _(createAudioConsumer(
          receiveTransport,
          consumerParams,
          {
            onTrackEnded: (_consumer) => {
              console.error('❌ Consumer track ended')
              roomStore.actions.setListenerError(listenerId, 'Audio track ended', 'error')
            }
          },
          { autoplay: true, volume: 0.8 }
        ).pipe(
          Effect.mapError(error => new ListenerFlowError({
            cause: `Failed to create consumer: ${String(error)}`,
            step: 'creating_consumer',
            stepNumber: 7,
            recoverable: false,
            context: { timestamp: new Date(), operation: 'create_consumer', details: { listenerId, error } }
          }))
        ))
        
        // Step 10a: Media streaming starts
        console.info('✅ Step 10a: Media streaming should start now')
        roomStore.actions.setListenerFlowStep(listenerId, 'streaming')
        
        const audioStream = new MediaStream([consumer.track])
        
        // Update listener state with consumer and audio stream
        roomStore.actions.updateListener(actualListenerId, {
          consumer: {
            ...initialListenerState.consumer,
            consumer: Option.some(consumer),
            id: Option.some(consumerParams.id),
            producerId: Option.some(consumerParams.producerId),
            kind: 'audio',
            paused: false,
            rtpParameters: Option.some(consumerParams.rtpParameters),
            track: Option.some(consumer.track),
            createdAt: Option.some(new Date())
          },
          audioPlayback: {
            ...initialListenerState.audioPlayback,
            mediaStream: Option.some(audioStream),
            volume: 0.8,
            muted: false,
            playing: true
          },
          flowCompletedAt: Option.some(new Date())
        })
        
        console.info('✅ Consumer and audio stream created successfully')
        
        // Set room metadata from join response
        const roomMetadata: RoomMetadata = {
          id: request.roomId,
          name: joinResponse.roomName,
          djName: joinResponse.djName,
          description: Option.fromNullable(joinResponse.description),
          isPublic: true,
          createdAt: new Date(joinResponse.createdAt),
          tags: []
        }
        
        roomStore.actions.setRoomMetadata(roomMetadata)
        
        console.info('🎉 Listener join flow completed successfully!')
        
        return {
          listenerId: actualListenerId,
          roomMetadata,
          audioStream
        }
        
      } catch (error) {
        console.error('❌ Listener join flow failed:', error)
        roomStore.actions.setListenerError(
          actualListenerId, 
          String(error), 
          'error'
        )
        throw error
      }
    })
  )

/**
 * Leave room as listener - cleanup flow
 */
export const leaveRoomAsListener = (
  roomStore: RoomStore,
  listenerId: string
): Effect.Effect<void, never> =>
  pipe(
    Effect.gen(function* (_) {
      console.info('👋 Leaving room as listener:', listenerId)
      
      // Get current listener state
      const listeners = roomStore.listeners
      const listener = listeners.find(l => (l as any).id === listenerId)
      
      if (listener) {
        // Cleanup MediaSoup resources
        Option.match(listener.consumer.consumer, {
          onSome: (consumer: any) => {
            console.info('Closing consumer')
            consumer.close()
          },
          onNone: () => {}
        })
        
        Option.match(listener.receiveTransport.transport, {
          onSome: (transport: any) => {
            console.info('Closing receive transport')
            transport.close()
          },
          onNone: () => {}
        })
        
        Option.match(listener.websocket.websocket, {
          onSome: (ws: any) => {
            console.info('Closing listener websocket')
            ws.close()
          },
          onNone: () => {}
        })
        
        // Remove listener from store
        roomStore.actions.removeListener(listenerId)
        console.info('Cleaned up listener resources and removed from store')
      }
      
      // If this was the last listener, disconnect from room
      if (roomStore.listenerCount === 0 && !roomStore.isDJStreaming) {
        yield* _(roomStore.actions.disconnectFromRoom())
      }
    })
  )

/**
 * Control audio playback for listener
 */
export const controlListenerAudio = (
  roomStore: RoomStore,
  listenerId: string,
  action: 'play' | 'pause' | 'setVolume',
  value?: number
): Effect.Effect<void, AudioPlaybackError> =>
  pipe(
    Effect.gen(function* (_) {
      const listeners = roomStore.listeners
      const listener = listeners.find(l => (l as any).id === listenerId)
      
      if (!listener) {
        yield* _(Effect.fail(new AudioPlaybackError({
          cause: `Listener ${listenerId} not found`,
          operation: 'play',
          autoplayBlocked: false,
          context: { timestamp: new Date(), operation: 'control_error', details: { listenerId, action } }
        })))
      }
      
      // Check if audio stream is available
      if (listener) {
        const hasAudioStream = Option.isSome(listener.audioPlayback.mediaStream)
        if (!hasAudioStream) {
          yield* _(Effect.fail(new AudioPlaybackError({
            cause: 'Audio stream not available',
            operation: action === 'setVolume' ? 'volume' : action,
            autoplayBlocked: false,
            context: { timestamp: new Date(), operation: 'stream_error', details: { listenerId, action } }
          })))
        }
      }
      
      switch (action) {
        case 'play':
          roomStore.actions.setListenerMuted(listenerId, false)
          break
        case 'pause':
          roomStore.actions.setListenerMuted(listenerId, true)
          break
        case 'setVolume':
          if (typeof value === 'number') {
            roomStore.actions.setListenerVolume(listenerId, value)
          }
          break
      }
    })
  )

// Helper functions for WebSocket event handling

/**
 * Wait for join room response
 */
function waitForJoinRoomResponse(
  lobbyWebSocket: WebSocket,
  roomId: string
): Effect.Effect<any, ListenerFlowError> {
  return Effect.async<any, ListenerFlowError>((resolve) => {
    const handleMessage = (event: MessageEvent) => {
      try {
        const message = JSON.parse(event.data)
        if (message.type === 'joinRoomResponse' && message.roomId === roomId) {
          lobbyWebSocket.removeEventListener('message', handleMessage)
          if (message.success) {
            resolve(Effect.succeed(message))
          } else {
            resolve(Effect.fail(new ListenerFlowError({
              cause: message.error || 'Failed to join room',
              step: 'requesting_join',
              stepNumber: 1,
              recoverable: false,
              context: { timestamp: new Date(), operation: 'join_room', details: { roomId } }
            })))
          }
        }
      } catch (error) {
        resolve(Effect.fail(new ListenerFlowError({
          cause: `Failed to parse join response: ${String(error)}`,
          step: 'requesting_join',
          stepNumber: 1,
          recoverable: false,
          context: { timestamp: new Date(), operation: 'parse_response', details: { roomId, error } }
        })))
      }
    }
    
    lobbyWebSocket.addEventListener('message', handleMessage)
    
    // Timeout after 10 seconds
    setTimeout(() => {
      lobbyWebSocket.removeEventListener('message', handleMessage)
      resolve(Effect.fail(new ListenerFlowError({
        cause: 'Timeout waiting for join room response',
        step: 'requesting_join', 
        stepNumber: 1,
        recoverable: true,
        context: { timestamp: new Date(), operation: 'wait_response', details: { roomId } }
      })))
    }, 10000)
  })
}

/**
 * Wait for WebSocket to open
 */
function waitForWebSocketOpen(ws: WebSocket): Effect.Effect<void, ListenerFlowError> {
  return Effect.async<void, ListenerFlowError>((resolve) => {
    if (ws.readyState === WebSocket.OPEN) {
      resolve(Effect.succeed(undefined))
      return
    }
    
    const handleOpen = () => {
      ws.removeEventListener('open', handleOpen)
      ws.removeEventListener('error', handleError)
      resolve(Effect.succeed(undefined))
    }
    
    const handleError = () => {
      ws.removeEventListener('open', handleOpen)
      ws.removeEventListener('error', handleError)
      resolve(Effect.fail(new ListenerFlowError({
        cause: 'WebSocket connection failed',
        step: 'requesting_join',
        stepNumber: 1,
        recoverable: false,
        context: { timestamp: new Date(), operation: 'websocket_connect', details: {} }
      })))
    }
    
    ws.addEventListener('open', handleOpen)
    ws.addEventListener('error', handleError)
  })
}

/**
 * Wait for transport parameters
 */
function waitForTransportParams(listenerWebSocket: WebSocket): Effect.Effect<any, ListenerFlowError> {
  return Effect.async<any, ListenerFlowError>((resolve) => {
    const handleMessage = (event: MessageEvent) => {
      try {
        const message = JSON.parse(event.data) as ListenerEvent
        if (message.type === 'listenerTransportReady') {
          listenerWebSocket.removeEventListener('message', handleMessage)
          resolve(Effect.succeed(message.transportOptions))
        }
      } catch (error) {
        // Continue listening for other messages
      }
    }
    
    listenerWebSocket.addEventListener('message', handleMessage)
    
    // Timeout after 10 seconds
    setTimeout(() => {
      listenerWebSocket.removeEventListener('message', handleMessage)
      resolve(Effect.fail(new ListenerFlowError({
        cause: 'Timeout waiting for transport parameters',
        step: 'waiting_transport_params',
        stepNumber: 2,
        recoverable: true,
        context: { timestamp: new Date(), operation: 'wait_transport', details: {} }
      })))
    }, 10000)
  })
}

/**
 * Wait for consumer result (success with params or error)
 */
function waitForConsumerResult(
  listenerWebSocket: WebSocket
): Effect.Effect<{ type: 'success'; params: any } | { type: 'error'; error: string }, ListenerFlowError> {
  return Effect.async<{ type: 'success'; params: any } | { type: 'error'; error: string }, ListenerFlowError>((resolve) => {
    const handleMessage = (event: MessageEvent) => {
      try {
        const message = JSON.parse(event.data) as ListenerEvent
        if (message.type === 'consumerCreated') {
          listenerWebSocket.removeEventListener('message', handleMessage)
          resolve(Effect.succeed({ type: 'success', params: message.consumerParameters }))
        } else if (message.type === 'commandFailed') {
          listenerWebSocket.removeEventListener('message', handleMessage)
          resolve(Effect.succeed({ type: 'error', error: message.error }))
        }
      } catch (error) {
        // Continue listening for other messages
      }
    }
    
    listenerWebSocket.addEventListener('message', handleMessage)
    
    // Timeout after 10 seconds
    setTimeout(() => {
      listenerWebSocket.removeEventListener('message', handleMessage)
      resolve(Effect.fail(new ListenerFlowError({
        cause: 'Timeout waiting for consumer result',
        step: 'waiting_consumer_check',
        stepNumber: 5,
        recoverable: true,
        context: { timestamp: new Date(), operation: 'wait_consumer', details: {} }
      })))
    }, 10000)
  })
}

