use mediasoup::{
    router::Router,
    webrtc_transport::{WebRtcTransport, WebRtcTransportOptions},
    prelude::*,
};
use serde_json::{json, Value};
use std::{net::{IpAddr, Ipv4Addr}, sync::Arc};
use uuid::Uuid;

/// Local network transport configuration for WiFi-only operation
#[derive(Clone)]
pub struct LocalTransportConfig {
    pub local_ip: IpAddr,
    pub port_range: Option<(u16, u16)>,
    pub enable_udp: bool,
    pub enable_tcp: bool,
}

impl Default for LocalTransportConfig {
    fn default() -> Self {
        Self {
            local_ip: IpAddr::V4(Ipv4Addr::new(0, 0, 0, 0)), // Bind to all interfaces
            port_range: Some((40000, 49999)),
            enable_udp: true,
            enable_tcp: false, // UDP preferred for local network
        }
    }
}

/// Transport manager for local WiFi network
#[derive(Clone)]
pub struct TransportManager {
    config: LocalTransportConfig,
}

impl TransportManager {
    pub fn new(config: LocalTransportConfig) -> Self {
        Self { config }
    }

    /// Create a WebRTC transport for DJ (sending audio)
    #[tracing::instrument(skip(self, router), fields(room_id = %room_id, transport_type = "dj", transport_id))]
    pub async fn create_dj_transport(
      &self,
      router: &Router,
      room_id: Uuid,
    ) -> anyhow::Result<(Arc<WebRtcTransport>, Value)> {

      // ✅ Get actual LAN IP for announcement
      let announced_ip = get_local_ip()?;

      let mut transport_options = WebRtcTransportOptions::new(
        WebRtcTransportListenInfos::new(ListenInfo {
          protocol: Protocol::Udp,
          ip: "0.0.0.0".parse().unwrap(),  // Bind all interfaces
          announced_address: Some(announced_ip.to_string()), // ✅ Announce 192.168.178.114!
          expose_internal_ip: false,
          port: None,
          port_range: None,
          flags: None,
          send_buffer_size: None,
          recv_buffer_size: None,
        })
      );

      transport_options.enable_udp = self.config.enable_udp;
      transport_options.enable_tcp = self.config.enable_tcp;
      transport_options.initial_available_outgoing_bitrate = 600000;

      let transport = router.create_webrtc_transport(transport_options).await?;

      // Use the actual WebRTC transport ID (generated by mediasoup)
      let transport_id = transport.id().to_string();

      // Record transport ID in span for tracing
      tracing::Span::current().record("transport_id", &transport_id);

      // ✅ Now ice_candidates will have 192.168.178.114:4000x
      let transport_options = self.generate_transport_options(&transport, &transport_id).await?;

      Ok((Arc::new(transport), transport_options))
    }

    /// Create a WebRTC transport for listener (receiving audio)
    #[tracing::instrument(skip(self, router), fields(room_id = %room_id, listener_id = %listener_id, transport_type = "listener", transport_id))]
    pub async fn create_listener_transport(
      &self,
      router: &Router,
      room_id: Uuid,
      listener_id: &str,
    ) -> anyhow::Result<(Arc<WebRtcTransport>, Value)> {

      // ✅ Get actual LAN IP
      let announced_ip = get_local_ip()?;

      let mut transport_options = WebRtcTransportOptions::new(
        WebRtcTransportListenInfos::new(ListenInfo {
          protocol: Protocol::Udp,
          ip: "0.0.0.0".parse().unwrap(),
          announced_address: Some(announced_ip.to_string()), // ✅ Critical!
          expose_internal_ip: false,
          port: None,
          port_range: None,
          flags: None,
          send_buffer_size: None,
          recv_buffer_size: None,
        })
      );

      transport_options.enable_udp = self.config.enable_udp;
      transport_options.enable_tcp = self.config.enable_tcp;
      transport_options.initial_available_outgoing_bitrate = 0;

      let transport = router.create_webrtc_transport(transport_options).await?;

      // Use the actual WebRTC transport ID (generated by mediasoup)
      let transport_id = transport.id().to_string();

      // Record transport ID in span for tracing
      tracing::Span::current().record("transport_id", &transport_id);

      let transport_options = self.generate_transport_options(&transport, &transport_id).await?;

      Ok((Arc::new(transport), transport_options))
    }

    /// Generate transport options for client connection (optimized for local network)
    async fn generate_transport_options(
      &self,
      transport: &WebRtcTransport,
      transport_id: &str,
    ) -> anyhow::Result<Value> {
      let ice_params = transport.ice_parameters();
      let dtls_params = transport.dtls_parameters();
      let ice_candidates = transport.ice_candidates(); // ✅ Include these!

      Ok(json!({
        "id": transport_id,
        "dtlsParameters": dtls_params,
        "iceCandidates": ice_candidates,
        "iceParameters": ice_params,
        "sctpParameters": null,
      }))
    }

    /// Connect transport with client's DTLS parameters
    #[tracing::instrument(skip(self, transport, dtls_parameters), fields(transport_id = %transport.id()))]
    pub async fn connect_transport(
        &self,
        transport: &WebRtcTransport,
        dtls_parameters: DtlsParameters,
    ) -> anyhow::Result<()> {
        // Parse DTLS parameters from client

        // Connect the transport
        transport.connect(WebRtcTransportRemoteParameters {
            dtls_parameters,
        }).await?;

        tracing::info!("WebRTC transport connected successfully");
        Ok(())
    }
}

impl Default for TransportManager {
    fn default() -> Self {
        Self::new(LocalTransportConfig::default())
    }
}

/// Helper to get local network IP address
pub fn get_local_ip() -> anyhow::Result<IpAddr> {
    use std::net::UdpSocket;

    // Connect to a dummy address to determine local IP
    let socket = UdpSocket::bind("0.0.0.0:0")?;
    socket.connect("8.8.8.8:80")?;
    let local_addr = socket.local_addr()?;

    Ok(local_addr.ip())
}

/// Configuration helper for common local network setups
impl LocalTransportConfig {
    /// Configuration for localhost development
    pub fn localhost() -> Self {
        Self {
            local_ip: IpAddr::V4(Ipv4Addr::LOCALHOST),
            port_range: Some((40000, 49999)),
            enable_udp: true,
            enable_tcp: false,
        }
    }

    /// Configuration for WiFi network (auto-detect local IP)
    pub fn wifi_network() -> anyhow::Result<Self> {
        let local_ip = get_local_ip()?;
        Ok(Self {
            local_ip,
            port_range: Some((40000, 49999)),
            enable_udp: true,
            enable_tcp: false,
        })
    }

    /// Configuration for specific network interface
    pub fn specific_ip(ip: IpAddr) -> Self {
        Self {
            local_ip: ip,
            port_range: Some((40000, 49999)),
            enable_udp: true,
            enable_tcp: false,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_transport_config() {
        let config = LocalTransportConfig::default();
        assert_eq!(config.local_ip, IpAddr::V4(Ipv4Addr::new(0, 0, 0, 0)));
        assert!(config.enable_udp);
        assert!(!config.enable_tcp);
    }

    #[test]
    fn test_localhost_config() {
        let config = LocalTransportConfig::localhost();
        assert_eq!(config.local_ip, IpAddr::V4(Ipv4Addr::LOCALHOST));
        assert!(config.enable_udp);
    }

    #[tokio::test]
    async fn test_get_local_ip() {
        let result = get_local_ip();
        assert!(result.is_ok());
    }
}
